// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e16990532af5f8dc11ae6c2d299e69e4ddc6894d/yamljs/yamljs.d.ts
declare namespace YAML {
    function load(path: string): any;

    function load(path: string, callback: (res:any) => void): void
	
    function stringify(nativeObject: any, inline?: number, spaces?: number): string;

    function parse(yamlString: string): any;
}

declare module "yamljs" {
    export = YAML;
}