System.config({
  baseURL: "./",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "app/ui/main.js",
      "github:es-shims/es6-shim@0.35.1.js",
      "github:es-shims/es6-shim@0.35.1/es6-shim.js",
      "app/ui/routing.js",
      "app/MyComponent.js",
      "npm:lodash@4.13.1.js",
      "npm:lodash@4.13.1/lodash.js",
      "npm:react@15.3.0.js",
      "npm:react@15.3.0/react.js",
      "npm:react@15.3.0/lib/React.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.6.js",
      "npm:process@0.11.6/browser.js",
      "npm:react@15.3.0/lib/ReactElementValidator.js",
      "npm:fbjs@0.8.3/lib/warning.js",
      "npm:fbjs@0.8.3/lib/emptyFunction.js",
      "npm:react@15.3.0/lib/getIteratorFn.js",
      "npm:react@15.3.0/lib/canDefineProperty.js",
      "npm:react@15.3.0/lib/checkReactTypeSpec.js",
      "npm:react@15.3.0/lib/ReactComponentTreeDevtool.js",
      "npm:fbjs@0.8.3/lib/invariant.js",
      "npm:react@15.3.0/lib/ReactCurrentOwner.js",
      "npm:react@15.3.0/lib/reactProdInvariant.js",
      "npm:react@15.3.0/lib/ReactPropTypesSecret.js",
      "npm:react@15.3.0/lib/ReactPropTypeLocationNames.js",
      "npm:react@15.3.0/lib/ReactPropTypeLocations.js",
      "npm:fbjs@0.8.3/lib/keyMirror.js",
      "npm:react@15.3.0/lib/ReactElement.js",
      "npm:object-assign@4.1.0.js",
      "npm:object-assign@4.1.0/index.js",
      "npm:react@15.3.0/lib/onlyChild.js",
      "npm:react@15.3.0/lib/ReactVersion.js",
      "npm:react@15.3.0/lib/ReactPropTypes.js",
      "npm:react@15.3.0/lib/ReactDOMFactories.js",
      "npm:fbjs@0.8.3/lib/mapObject.js",
      "npm:react@15.3.0/lib/ReactClass.js",
      "npm:fbjs@0.8.3/lib/keyOf.js",
      "npm:fbjs@0.8.3/lib/emptyObject.js",
      "npm:react@15.3.0/lib/ReactNoopUpdateQueue.js",
      "npm:react@15.3.0/lib/ReactComponent.js",
      "npm:react@15.3.0/lib/ReactPureComponent.js",
      "npm:react@15.3.0/lib/ReactChildren.js",
      "npm:react@15.3.0/lib/traverseAllChildren.js",
      "npm:react@15.3.0/lib/KeyEscapeUtils.js",
      "npm:react@15.3.0/lib/PooledClass.js",
      "app/ui/pages/CmTopLogo.js",
      "app/ui/complexity-table/CmComplexityTable.js",
      "app/react-ext/decorators.js",
      "app/ui/charts/CmChartSuite.js",
      "app/ui/charts/CmChartGroup.js",
      "app/ui/charts/CmChart.js",
      "github:chartjs/Chart.js@2.1.6.js",
      "github:chartjs/Chart.js@2.1.6/src/chart.js",
      "github:chartjs/Chart.js@2.1.6/src/charts/Chart.Scatter.js",
      "github:chartjs/Chart.js@2.1.6/src/charts/Chart.Radar.js",
      "github:chartjs/Chart.js@2.1.6/src/charts/Chart.PolarArea.js",
      "github:chartjs/Chart.js@2.1.6/src/charts/Chart.Line.js",
      "github:chartjs/Chart.js@2.1.6/src/charts/Chart.Doughnut.js",
      "github:chartjs/Chart.js@2.1.6/src/charts/Chart.Bubble.js",
      "github:chartjs/Chart.js@2.1.6/src/charts/Chart.Bar.js",
      "github:chartjs/Chart.js@2.1.6/src/controllers/controller.radar.js",
      "github:chartjs/Chart.js@2.1.6/src/controllers/controller.polarArea.js",
      "github:chartjs/Chart.js@2.1.6/src/controllers/controller.line.js",
      "github:chartjs/Chart.js@2.1.6/src/controllers/controller.doughnut.js",
      "github:chartjs/Chart.js@2.1.6/src/controllers/controller.bubble.js",
      "github:chartjs/Chart.js@2.1.6/src/controllers/controller.bar.js",
      "github:chartjs/Chart.js@2.1.6/src/scales/scale.time.js",
      "npm:moment@2.14.1.js",
      "npm:moment@2.14.1/moment.js",
      "github:chartjs/Chart.js@2.1.6/src/scales/scale.radialLinear.js",
      "github:chartjs/Chart.js@2.1.6/src/scales/scale.logarithmic.js",
      "github:chartjs/Chart.js@2.1.6/src/scales/scale.linear.js",
      "github:chartjs/Chart.js@2.1.6/src/scales/scale.category.js",
      "github:chartjs/Chart.js@2.1.6/src/scales/scale.linearbase.js",
      "github:chartjs/Chart.js@2.1.6/src/elements/element.rectangle.js",
      "github:chartjs/Chart.js@2.1.6/src/elements/element.point.js",
      "github:chartjs/Chart.js@2.1.6/src/elements/element.line.js",
      "github:chartjs/Chart.js@2.1.6/src/elements/element.arc.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.tooltip.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.legend.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.title.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.scale.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.plugin.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.scaleService.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.layoutService.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.datasetController.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.controller.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.animation.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.element.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.helpers.js",
      "npm:chartjs-color@2.0.0.js",
      "npm:chartjs-color@2.0.0/index.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:chartjs-color-string@0.4.0.js",
      "npm:chartjs-color-string@0.4.0/color-string.js",
      "npm:color-name@1.1.1.js",
      "npm:color-name@1.1.1/index.js",
      "npm:color-convert@0.5.3.js",
      "npm:color-convert@0.5.3/index.js",
      "npm:color-convert@0.5.3/conversions.js",
      "github:chartjs/Chart.js@2.1.6/src/core/core.js",
      "app/ui/markdown/CmMarkdown.js",
      "npm:react-markdown@2.4.2.js",
      "npm:react-markdown@2.4.2/src/react-markdown.js",
      "npm:commonmark-react-renderer@4.2.4.js",
      "npm:commonmark-react-renderer@4.2.4/src/commonmark-react-renderer.js",
      "npm:xss-filters@1.2.6.js",
      "npm:xss-filters@1.2.6/src/xss-filters.js",
      "npm:lodash.isplainobject@4.0.4.js",
      "npm:lodash.isplainobject@4.0.4/index.js",
      "npm:lodash.assign@4.0.9.js",
      "npm:lodash.assign@4.0.9/index.js",
      "npm:lodash.rest@4.0.3.js",
      "npm:lodash.rest@4.0.3/index.js",
      "npm:lodash.keys@4.0.7.js",
      "npm:lodash.keys@4.0.7/index.js",
      "npm:commonmark@0.24.0.js",
      "npm:commonmark@0.24.0/lib/index.js",
      "npm:commonmark@0.24.0/lib/xml.js",
      "npm:commonmark@0.24.0/lib/common.js",
      "npm:entities@1.1.1.js",
      "npm:entities@1.1.1/index.js",
      "npm:entities@1.1.1/lib/decode.js",
      "npm:entities@1.1.1/lib/decode_codepoint.js",
      "npm:entities@1.1.1/maps/decode.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:entities@1.1.1/maps/xml.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:entities@1.1.1/maps/legacy.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:entities@1.1.1/maps/entities.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:entities@1.1.1/lib/encode.js",
      "npm:mdurl@1.0.1/decode.js",
      "npm:mdurl@1.0.1/encode.js",
      "npm:commonmark@0.24.0/lib/html.js",
      "npm:commonmark@0.24.0/lib/blocks.js",
      "npm:commonmark@0.24.0/lib/inlines.js",
      "npm:string.prototype.repeat@0.2.0.js",
      "npm:string.prototype.repeat@0.2.0/repeat.js",
      "npm:commonmark@0.24.0/lib/from-code-point.js",
      "npm:commonmark@0.24.0/lib/normalize-reference.js",
      "npm:commonmark@0.24.0/lib/node.js",
      "npm:react-highlight@0.8.0.js",
      "npm:react-highlight@0.8.0/index.js",
      "npm:react-highlight@0.8.0/lib/index.js",
      "npm:react-dom@15.3.0.js",
      "npm:react-dom@15.3.0/index.js",
      "npm:react@15.3.0/lib/ReactDOM.js",
      "npm:fbjs@0.8.3/lib/ExecutionEnvironment.js",
      "npm:react@15.3.0/lib/renderSubtreeIntoContainer.js",
      "npm:react@15.3.0/lib/ReactMount.js",
      "npm:react@15.3.0/lib/shouldUpdateReactComponent.js",
      "npm:react@15.3.0/lib/setInnerHTML.js",
      "npm:react@15.3.0/lib/createMicrosoftUnsafeLocalFunction.js",
      "npm:react@15.3.0/lib/DOMNamespaces.js",
      "npm:react@15.3.0/lib/instantiateReactComponent.js",
      "npm:react@15.3.0/lib/ReactInstrumentation.js",
      "npm:react@15.3.0/lib/ReactDebugTool.js",
      "npm:fbjs@0.8.3/lib/performanceNow.js",
      "npm:fbjs@0.8.3/lib/performance.js",
      "npm:react@15.3.0/lib/ReactChildrenMutationWarningDevtool.js",
      "npm:react@15.3.0/lib/ReactHostOperationHistoryDevtool.js",
      "npm:react@15.3.0/lib/ReactInvalidSetStateWarningDevTool.js",
      "npm:react@15.3.0/lib/ReactHostComponent.js",
      "npm:react@15.3.0/lib/ReactEmptyComponent.js",
      "npm:react@15.3.0/lib/ReactCompositeComponent.js",
      "npm:fbjs@0.8.3/lib/shallowEqual.js",
      "npm:react@15.3.0/lib/ReactReconciler.js",
      "npm:react@15.3.0/lib/ReactRef.js",
      "npm:react@15.3.0/lib/ReactOwner.js",
      "npm:react@15.3.0/lib/ReactNodeTypes.js",
      "npm:react@15.3.0/lib/ReactInstanceMap.js",
      "npm:react@15.3.0/lib/ReactErrorUtils.js",
      "npm:react@15.3.0/lib/ReactComponentEnvironment.js",
      "npm:react@15.3.0/lib/ReactUpdates.js",
      "npm:react@15.3.0/lib/Transaction.js",
      "npm:react@15.3.0/lib/ReactFeatureFlags.js",
      "npm:react@15.3.0/lib/CallbackQueue.js",
      "npm:react@15.3.0/lib/ReactUpdateQueue.js",
      "npm:react@15.3.0/lib/ReactMarkupChecksum.js",
      "npm:react@15.3.0/lib/adler32.js",
      "npm:react@15.3.0/lib/ReactDOMFeatureFlags.js",
      "npm:react@15.3.0/lib/ReactDOMContainerInfo.js",
      "npm:react@15.3.0/lib/validateDOMNesting.js",
      "npm:react@15.3.0/lib/ReactDOMComponentTree.js",
      "npm:react@15.3.0/lib/ReactDOMComponentFlags.js",
      "npm:react@15.3.0/lib/DOMProperty.js",
      "npm:react@15.3.0/lib/ReactBrowserEventEmitter.js",
      "npm:react@15.3.0/lib/isEventSupported.js",
      "npm:react@15.3.0/lib/getVendorPrefixedEventName.js",
      "npm:react@15.3.0/lib/ViewportMetrics.js",
      "npm:react@15.3.0/lib/ReactEventEmitterMixin.js",
      "npm:react@15.3.0/lib/EventPluginHub.js",
      "npm:react@15.3.0/lib/forEachAccumulated.js",
      "npm:react@15.3.0/lib/accumulateInto.js",
      "npm:react@15.3.0/lib/EventPluginUtils.js",
      "npm:react@15.3.0/lib/EventConstants.js",
      "npm:react@15.3.0/lib/EventPluginRegistry.js",
      "npm:react@15.3.0/lib/DOMLazyTree.js",
      "npm:react@15.3.0/lib/setTextContent.js",
      "npm:react@15.3.0/lib/escapeTextContentForBrowser.js",
      "npm:react@15.3.0/lib/getHostComponentFromComposite.js",
      "npm:react@15.3.0/lib/findDOMNode.js",
      "npm:react@15.3.0/lib/ReactDefaultInjection.js",
      "npm:react@15.3.0/lib/SimpleEventPlugin.js",
      "npm:react@15.3.0/lib/getEventCharCode.js",
      "npm:react@15.3.0/lib/SyntheticWheelEvent.js",
      "npm:react@15.3.0/lib/SyntheticMouseEvent.js",
      "npm:react@15.3.0/lib/getEventModifierState.js",
      "npm:react@15.3.0/lib/SyntheticUIEvent.js",
      "npm:react@15.3.0/lib/getEventTarget.js",
      "npm:react@15.3.0/lib/SyntheticEvent.js",
      "npm:react@15.3.0/lib/SyntheticTransitionEvent.js",
      "npm:react@15.3.0/lib/SyntheticTouchEvent.js",
      "npm:react@15.3.0/lib/SyntheticDragEvent.js",
      "npm:react@15.3.0/lib/SyntheticKeyboardEvent.js",
      "npm:react@15.3.0/lib/getEventKey.js",
      "npm:react@15.3.0/lib/SyntheticFocusEvent.js",
      "npm:react@15.3.0/lib/SyntheticClipboardEvent.js",
      "npm:react@15.3.0/lib/SyntheticAnimationEvent.js",
      "npm:react@15.3.0/lib/EventPropagators.js",
      "npm:fbjs@0.8.3/lib/EventListener.js",
      "npm:react@15.3.0/lib/SelectEventPlugin.js",
      "npm:react@15.3.0/lib/isTextInputElement.js",
      "npm:fbjs@0.8.3/lib/getActiveElement.js",
      "npm:react@15.3.0/lib/ReactInputSelection.js",
      "npm:fbjs@0.8.3/lib/focusNode.js",
      "npm:fbjs@0.8.3/lib/containsNode.js",
      "npm:fbjs@0.8.3/lib/isTextNode.js",
      "npm:fbjs@0.8.3/lib/isNode.js",
      "npm:react@15.3.0/lib/ReactDOMSelection.js",
      "npm:react@15.3.0/lib/getTextContentAccessor.js",
      "npm:react@15.3.0/lib/getNodeForCharacterOffset.js",
      "npm:react@15.3.0/lib/SVGDOMPropertyConfig.js",
      "npm:react@15.3.0/lib/ReactReconcileTransaction.js",
      "npm:react@15.3.0/lib/ReactInjection.js",
      "npm:react@15.3.0/lib/ReactEventListener.js",
      "npm:fbjs@0.8.3/lib/getUnboundedScrollPosition.js",
      "npm:react@15.3.0/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@15.3.0/lib/ReactDOMTextComponent.js",
      "npm:react@15.3.0/lib/DOMChildrenOperations.js",
      "npm:react@15.3.0/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@15.3.0/lib/Danger.js",
      "npm:fbjs@0.8.3/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.8.3/lib/getMarkupWrap.js",
      "npm:fbjs@0.8.3/lib/createArrayFromMixed.js",
      "npm:react@15.3.0/lib/ReactDOMTreeTraversal.js",
      "npm:react@15.3.0/lib/ReactDOMEmptyComponent.js",
      "npm:react@15.3.0/lib/ReactDOMComponent.js",
      "npm:react@15.3.0/lib/ReactServerRenderingTransaction.js",
      "npm:react@15.3.0/lib/ReactServerUpdateQueue.js",
      "npm:react@15.3.0/lib/ReactMultiChild.js",
      "npm:react@15.3.0/lib/flattenChildren.js",
      "npm:react@15.3.0/lib/ReactChildReconciler.js",
      "npm:react@15.3.0/lib/ReactDOMTextarea.js",
      "npm:react@15.3.0/lib/LinkedValueUtils.js",
      "npm:react@15.3.0/lib/DisabledInputUtils.js",
      "npm:react@15.3.0/lib/ReactDOMSelect.js",
      "npm:react@15.3.0/lib/ReactDOMOption.js",
      "npm:react@15.3.0/lib/ReactDOMInput.js",
      "npm:react@15.3.0/lib/DOMPropertyOperations.js",
      "npm:react@15.3.0/lib/quoteAttributeValueForBrowser.js",
      "npm:react@15.3.0/lib/ReactDOMInstrumentation.js",
      "npm:react@15.3.0/lib/ReactDOMDebugTool.js",
      "npm:react@15.3.0/lib/ReactDOMUnknownPropertyDevtool.js",
      "npm:react@15.3.0/lib/ReactDOMNullInputValuePropDevtool.js",
      "npm:react@15.3.0/lib/ReactDOMButton.js",
      "npm:react@15.3.0/lib/ReactComponentBrowserEnvironment.js",
      "npm:react@15.3.0/lib/ReactDOMIDOperations.js",
      "npm:react@15.3.0/lib/CSSPropertyOperations.js",
      "npm:fbjs@0.8.3/lib/memoizeStringOnly.js",
      "npm:fbjs@0.8.3/lib/hyphenateStyleName.js",
      "npm:fbjs@0.8.3/lib/hyphenate.js",
      "npm:react@15.3.0/lib/dangerousStyleValue.js",
      "npm:react@15.3.0/lib/CSSProperty.js",
      "npm:fbjs@0.8.3/lib/camelizeStyleName.js",
      "npm:fbjs@0.8.3/lib/camelize.js",
      "npm:react@15.3.0/lib/AutoFocusUtils.js",
      "npm:react@15.3.0/lib/HTMLDOMPropertyConfig.js",
      "npm:react@15.3.0/lib/EnterLeaveEventPlugin.js",
      "npm:react@15.3.0/lib/DefaultEventPluginOrder.js",
      "npm:react@15.3.0/lib/ChangeEventPlugin.js",
      "npm:react@15.3.0/lib/BeforeInputEventPlugin.js",
      "npm:react@15.3.0/lib/SyntheticInputEvent.js",
      "npm:react@15.3.0/lib/SyntheticCompositionEvent.js",
      "npm:react@15.3.0/lib/FallbackCompositionState.js",
      "npm:highlight.js@8.9.1.js",
      "npm:highlight.js@8.9.1/lib/index.js",
      "npm:highlight.js@8.9.1/lib/languages/zephir.js",
      "npm:highlight.js@8.9.1/lib/languages/xquery.js",
      "npm:highlight.js@8.9.1/lib/languages/xl.js",
      "npm:highlight.js@8.9.1/lib/languages/x86asm.js",
      "npm:highlight.js@8.9.1/lib/languages/vim.js",
      "npm:highlight.js@8.9.1/lib/languages/vhdl.js",
      "npm:highlight.js@8.9.1/lib/languages/verilog.js",
      "npm:highlight.js@8.9.1/lib/languages/vbscript-html.js",
      "npm:highlight.js@8.9.1/lib/languages/vbscript.js",
      "npm:highlight.js@8.9.1/lib/languages/vbnet.js",
      "npm:highlight.js@8.9.1/lib/languages/vala.js",
      "npm:highlight.js@8.9.1/lib/languages/typescript.js",
      "npm:highlight.js@8.9.1/lib/languages/twig.js",
      "npm:highlight.js@8.9.1/lib/languages/tp.js",
      "npm:highlight.js@8.9.1/lib/languages/thrift.js",
      "npm:highlight.js@8.9.1/lib/languages/tex.js",
      "npm:highlight.js@8.9.1/lib/languages/tcl.js",
      "npm:highlight.js@8.9.1/lib/languages/swift.js",
      "npm:highlight.js@8.9.1/lib/languages/stylus.js",
      "npm:highlight.js@8.9.1/lib/languages/step21.js",
      "npm:highlight.js@8.9.1/lib/languages/stata.js",
      "npm:highlight.js@8.9.1/lib/languages/sql.js",
      "npm:highlight.js@8.9.1/lib/languages/sqf.js",
      "npm:highlight.js@8.9.1/lib/languages/sml.js",
      "npm:highlight.js@8.9.1/lib/languages/smalltalk.js",
      "npm:highlight.js@8.9.1/lib/languages/smali.js",
      "npm:highlight.js@8.9.1/lib/languages/scss.js",
      "npm:highlight.js@8.9.1/lib/languages/scilab.js",
      "npm:highlight.js@8.9.1/lib/languages/scheme.js",
      "npm:highlight.js@8.9.1/lib/languages/scala.js",
      "npm:highlight.js@8.9.1/lib/languages/rust.js",
      "npm:highlight.js@8.9.1/lib/languages/ruleslanguage.js",
      "npm:highlight.js@8.9.1/lib/languages/rsl.js",
      "npm:highlight.js@8.9.1/lib/languages/roboconf.js",
      "npm:highlight.js@8.9.1/lib/languages/rib.js",
      "npm:highlight.js@8.9.1/lib/languages/r.js",
      "npm:highlight.js@8.9.1/lib/languages/q.js",
      "npm:highlight.js@8.9.1/lib/languages/python.js",
      "npm:highlight.js@8.9.1/lib/languages/puppet.js",
      "npm:highlight.js@8.9.1/lib/languages/protobuf.js",
      "npm:highlight.js@8.9.1/lib/languages/prolog.js",
      "npm:highlight.js@8.9.1/lib/languages/profile.js",
      "npm:highlight.js@8.9.1/lib/languages/processing.js",
      "npm:highlight.js@8.9.1/lib/languages/powershell.js",
      "npm:highlight.js@8.9.1/lib/languages/php.js",
      "npm:highlight.js@8.9.1/lib/languages/pf.js",
      "npm:highlight.js@8.9.1/lib/languages/parser3.js",
      "npm:highlight.js@8.9.1/lib/languages/oxygene.js",
      "npm:highlight.js@8.9.1/lib/languages/openscad.js",
      "npm:highlight.js@8.9.1/lib/languages/ocaml.js",
      "npm:highlight.js@8.9.1/lib/languages/objectivec.js",
      "npm:highlight.js@8.9.1/lib/languages/nsis.js",
      "npm:highlight.js@8.9.1/lib/languages/nix.js",
      "npm:highlight.js@8.9.1/lib/languages/nimrod.js",
      "npm:highlight.js@8.9.1/lib/languages/nginx.js",
      "npm:highlight.js@8.9.1/lib/languages/monkey.js",
      "npm:highlight.js@8.9.1/lib/languages/mojolicious.js",
      "npm:highlight.js@8.9.1/lib/languages/perl.js",
      "npm:highlight.js@8.9.1/lib/languages/mizar.js",
      "npm:highlight.js@8.9.1/lib/languages/mercury.js",
      "npm:highlight.js@8.9.1/lib/languages/mel.js",
      "npm:highlight.js@8.9.1/lib/languages/matlab.js",
      "npm:highlight.js@8.9.1/lib/languages/mathematica.js",
      "npm:highlight.js@8.9.1/lib/languages/makefile.js",
      "npm:highlight.js@8.9.1/lib/languages/lua.js",
      "npm:highlight.js@8.9.1/lib/languages/livescript.js",
      "npm:highlight.js@8.9.1/lib/languages/livecodeserver.js",
      "npm:highlight.js@8.9.1/lib/languages/lisp.js",
      "npm:highlight.js@8.9.1/lib/languages/less.js",
      "npm:highlight.js@8.9.1/lib/languages/lasso.js",
      "npm:highlight.js@8.9.1/lib/languages/kotlin.js",
      "npm:highlight.js@8.9.1/lib/languages/julia.js",
      "npm:highlight.js@8.9.1/lib/languages/json.js",
      "npm:highlight.js@8.9.1/lib/languages/javascript.js",
      "npm:highlight.js@8.9.1/lib/languages/java.js",
      "npm:highlight.js@8.9.1/lib/languages/irpf90.js",
      "npm:highlight.js@8.9.1/lib/languages/ini.js",
      "npm:highlight.js@8.9.1/lib/languages/inform7.js",
      "npm:highlight.js@8.9.1/lib/languages/http.js",
      "npm:highlight.js@8.9.1/lib/languages/haxe.js",
      "npm:highlight.js@8.9.1/lib/languages/haskell.js",
      "npm:highlight.js@8.9.1/lib/languages/handlebars.js",
      "npm:highlight.js@8.9.1/lib/languages/haml.js",
      "npm:highlight.js@8.9.1/lib/languages/groovy.js",
      "npm:highlight.js@8.9.1/lib/languages/gradle.js",
      "npm:highlight.js@8.9.1/lib/languages/golo.js",
      "npm:highlight.js@8.9.1/lib/languages/go.js",
      "npm:highlight.js@8.9.1/lib/languages/glsl.js",
      "npm:highlight.js@8.9.1/lib/languages/gherkin.js",
      "npm:highlight.js@8.9.1/lib/languages/gcode.js",
      "npm:highlight.js@8.9.1/lib/languages/gams.js",
      "npm:highlight.js@8.9.1/lib/languages/fsharp.js",
      "npm:highlight.js@8.9.1/lib/languages/fortran.js",
      "npm:highlight.js@8.9.1/lib/languages/fix.js",
      "npm:highlight.js@8.9.1/lib/languages/erlang.js",
      "npm:highlight.js@8.9.1/lib/languages/erlang-repl.js",
      "npm:highlight.js@8.9.1/lib/languages/erb.js",
      "npm:highlight.js@8.9.1/lib/languages/ruby.js",
      "npm:highlight.js@8.9.1/lib/languages/elm.js",
      "npm:highlight.js@8.9.1/lib/languages/elixir.js",
      "npm:highlight.js@8.9.1/lib/languages/dust.js",
      "npm:highlight.js@8.9.1/lib/languages/dos.js",
      "npm:highlight.js@8.9.1/lib/languages/dockerfile.js",
      "npm:highlight.js@8.9.1/lib/languages/dns.js",
      "npm:highlight.js@8.9.1/lib/languages/django.js",
      "npm:highlight.js@8.9.1/lib/languages/diff.js",
      "npm:highlight.js@8.9.1/lib/languages/delphi.js",
      "npm:highlight.js@8.9.1/lib/languages/dart.js",
      "npm:highlight.js@8.9.1/lib/languages/markdown.js",
      "npm:highlight.js@8.9.1/lib/languages/d.js",
      "npm:highlight.js@8.9.1/lib/languages/css.js",
      "npm:highlight.js@8.9.1/lib/languages/cs.js",
      "npm:highlight.js@8.9.1/lib/languages/crystal.js",
      "npm:highlight.js@8.9.1/lib/languages/crmsh.js",
      "npm:highlight.js@8.9.1/lib/languages/cpp.js",
      "npm:highlight.js@8.9.1/lib/languages/coffeescript.js",
      "npm:highlight.js@8.9.1/lib/languages/cmake.js",
      "npm:highlight.js@8.9.1/lib/languages/clojure-repl.js",
      "npm:highlight.js@8.9.1/lib/languages/clojure.js",
      "npm:highlight.js@8.9.1/lib/languages/ceylon.js",
      "npm:highlight.js@8.9.1/lib/languages/capnproto.js",
      "npm:highlight.js@8.9.1/lib/languages/cal.js",
      "npm:highlight.js@8.9.1/lib/languages/brainfuck.js",
      "npm:highlight.js@8.9.1/lib/languages/bash.js",
      "npm:highlight.js@8.9.1/lib/languages/axapta.js",
      "npm:highlight.js@8.9.1/lib/languages/avrasm.js",
      "npm:highlight.js@8.9.1/lib/languages/autoit.js",
      "npm:highlight.js@8.9.1/lib/languages/autohotkey.js",
      "npm:highlight.js@8.9.1/lib/languages/aspectj.js",
      "npm:highlight.js@8.9.1/lib/languages/asciidoc.js",
      "npm:highlight.js@8.9.1/lib/languages/xml.js",
      "npm:highlight.js@8.9.1/lib/languages/armasm.js",
      "npm:highlight.js@8.9.1/lib/languages/applescript.js",
      "npm:highlight.js@8.9.1/lib/languages/apache.js",
      "npm:highlight.js@8.9.1/lib/languages/actionscript.js",
      "npm:highlight.js@8.9.1/lib/languages/accesslog.js",
      "npm:highlight.js@8.9.1/lib/languages/1c.js",
      "npm:highlight.js@8.9.1/lib/highlight.js",
      "npm:react-router@2.6.1.js",
      "npm:react-router@2.6.1/lib/index.js",
      "npm:react-router@2.6.1/lib/createMemoryHistory.js",
      "npm:history@2.1.2/lib/createMemoryHistory.js",
      "npm:history@2.1.2/lib/createHistory.js",
      "npm:history@2.1.2/lib/deprecate.js",
      "npm:warning@2.1.0.js",
      "npm:warning@2.1.0/browser.js",
      "npm:history@2.1.2/lib/runTransitionHook.js",
      "npm:history@2.1.2/lib/createLocation.js",
      "npm:history@2.1.2/lib/PathUtils.js",
      "npm:history@2.1.2/lib/Actions.js",
      "npm:history@2.1.2/lib/AsyncUtils.js",
      "npm:deep-equal@1.0.1.js",
      "npm:deep-equal@1.0.1/index.js",
      "npm:deep-equal@1.0.1/lib/is_arguments.js",
      "npm:deep-equal@1.0.1/lib/keys.js",
      "npm:invariant@2.2.1.js",
      "npm:invariant@2.2.1/browser.js",
      "npm:history@2.1.2/lib/useBasename.js",
      "npm:history@2.1.2/lib/ExecutionEnvironment.js",
      "npm:history@2.1.2/lib/useQueries.js",
      "npm:query-string@3.0.3.js",
      "npm:query-string@3.0.3/index.js",
      "npm:strict-uri-encode@1.1.0.js",
      "npm:strict-uri-encode@1.1.0/index.js",
      "npm:react-router@2.6.1/lib/hashHistory.js",
      "npm:react-router@2.6.1/lib/createRouterHistory.js",
      "npm:react-router@2.6.1/lib/useRouterHistory.js",
      "npm:history@2.1.2/lib/createHashHistory.js",
      "npm:history@2.1.2/lib/createDOMHistory.js",
      "npm:history@2.1.2/lib/DOMUtils.js",
      "npm:history@2.1.2/lib/DOMStateStorage.js",
      "npm:react-router@2.6.1/lib/browserHistory.js",
      "npm:history@2.1.2/lib/createBrowserHistory.js",
      "npm:react-router@2.6.1/lib/applyRouterMiddleware.js",
      "npm:react-router@2.6.1/lib/RouterContext.js",
      "npm:react-router@2.6.1/lib/routerWarning.js",
      "npm:warning@3.0.0.js",
      "npm:warning@3.0.0/browser.js",
      "npm:react-router@2.6.1/lib/RouteUtils.js",
      "npm:react-router@2.6.1/lib/getRouteParams.js",
      "npm:react-router@2.6.1/lib/PatternUtils.js",
      "npm:react-router@2.6.1/lib/deprecateObjectProperties.js",
      "npm:react-router@2.6.1/lib/match.js",
      "npm:react-router@2.6.1/lib/RouterUtils.js",
      "npm:react-router@2.6.1/lib/createTransitionManager.js",
      "npm:react-router@2.6.1/lib/matchRoutes.js",
      "npm:react-router@2.6.1/lib/makeStateWithLocation.js",
      "npm:react-router@2.6.1/lib/AsyncUtils.js",
      "npm:react-router@2.6.1/lib/getComponents.js",
      "npm:react-router@2.6.1/lib/isActive.js",
      "npm:react-router@2.6.1/lib/TransitionUtils.js",
      "npm:react-router@2.6.1/lib/computeChangedRoutes.js",
      "npm:react-router@2.6.1/lib/RoutingContext.js",
      "npm:react-router@2.6.1/lib/useRoutes.js",
      "npm:react-router@2.6.1/lib/RouteContext.js",
      "npm:react-router@2.6.1/lib/Lifecycle.js",
      "npm:react-router@2.6.1/lib/History.js",
      "npm:react-router@2.6.1/lib/InternalPropTypes.js",
      "npm:react-router@2.6.1/lib/Route.js",
      "npm:react-router@2.6.1/lib/Redirect.js",
      "npm:react-router@2.6.1/lib/IndexRoute.js",
      "npm:react-router@2.6.1/lib/IndexRedirect.js",
      "npm:react-router@2.6.1/lib/withRouter.js",
      "npm:react-router@2.6.1/lib/PropTypes.js",
      "npm:hoist-non-react-statics@1.2.0.js",
      "npm:hoist-non-react-statics@1.2.0/index.js",
      "npm:react-router@2.6.1/lib/IndexLink.js",
      "npm:react-router@2.6.1/lib/Link.js",
      "npm:react-router@2.6.1/lib/Router.js",
      "npm:jquery@3.1.0.js",
      "npm:jquery@3.1.0/dist/jquery.js",
      "app/ui/CmMathjaxMacros.js",
      "app/ui/navbar/CmArticleNav.js",
      "app/ui/api.js",
      "app/ui/charts/types.js",
      "npm:yamljs@0.2.8.js",
      "npm:yamljs@0.2.8/lib/Yaml.js",
      "npm:yamljs@0.2.8/lib/Utils.js",
      "npm:yamljs@0.2.8/lib/Pattern.js",
      "npm:yamljs@0.2.8/lib/Dumper.js",
      "npm:yamljs@0.2.8/lib/Inline.js",
      "npm:yamljs@0.2.8/lib/Exception/DumpException.js",
      "npm:yamljs@0.2.8/lib/Exception/ParseException.js",
      "npm:yamljs@0.2.8/lib/Escaper.js",
      "npm:yamljs@0.2.8/lib/Unescaper.js",
      "npm:yamljs@0.2.8/lib/Parser.js",
      "app/ui/data.js",
      "app/ui/links.js"
    ]
  },

  map: {
    "chai": "npm:chai@3.5.0",
    "chart": "github:chartjs/Chart.js@2.1.6",
    "chartjs-color": "npm:chartjs-color@2.0.0",
    "css": "github:systemjs/plugin-css@0.1.26",
    "es6-shim": "github:es-shims/es6-shim@0.35.1",
    "highlightjs": "github:components/highlightjs@9.5.0",
    "jquery": "npm:jquery@3.1.0",
    "lodash": "npm:lodash@4.13.1",
    "moment": "npm:moment@2.14.1",
    "react": "npm:react@15.3.0",
    "react-dom": "npm:react-dom@15.3.0",
    "react-highlight": "npm:react-highlight@0.8.0",
    "react-markdown": "npm:react-markdown@2.4.2",
    "react-router": "npm:react-router@2.6.1",
    "yamljs": "npm:yamljs@0.2.8",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.7"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.6"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "npm:argparse@1.0.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "sprintf-js": "npm:sprintf-js@1.0.3",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:asap@2.0.4": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:brace-expansion@1.1.6": {
      "balanced-match": "npm:balanced-match@0.4.2",
      "concat-map": "npm:concat-map@0.0.1"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.9",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@2.1.4",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer-shims@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:chai@3.5.0": {
      "assertion-error": "npm:assertion-error@1.0.2",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "deep-eql": "npm:deep-eql@0.1.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "type-detect": "npm:type-detect@1.0.0"
    },
    "npm:chartjs-color-string@0.4.0": {
      "color-name": "npm:color-name@1.1.1"
    },
    "npm:chartjs-color@2.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "chartjs-color-string": "npm:chartjs-color-string@0.4.0",
      "color-convert": "npm:color-convert@0.5.3"
    },
    "npm:commonmark-react-renderer@4.2.4": {
      "commonmark": "npm:commonmark@0.24.0",
      "lodash.assign": "npm:lodash.assign@4.0.9",
      "lodash.isplainobject": "npm:lodash.isplainobject@4.0.4",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.0",
      "xss-filters": "npm:xss-filters@1.2.6"
    },
    "npm:commonmark@0.24.0": {
      "entities": "npm:entities@1.1.1",
      "mdurl": "npm:mdurl@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "string.prototype.repeat": "npm:string.prototype.repeat@0.2.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:deep-eql@0.1.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "type-detect": "npm:type-detect@0.1.1"
    },
    "npm:domain-browser@1.1.7": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:encoding@0.1.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "iconv-lite": "npm:iconv-lite@0.4.13"
    },
    "npm:entities@1.1.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:fbjs@0.8.3": {
      "core-js": "npm:core-js@1.2.7",
      "immutable": "npm:immutable@3.8.1",
      "isomorphic-fetch": "npm:isomorphic-fetch@2.2.1",
      "loose-envify": "npm:loose-envify@1.2.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.1.1",
      "ua-parser-js": "npm:ua-parser-js@0.7.10"
    },
    "npm:fs.realpath@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:glob@7.0.5": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "fs.realpath": "npm:fs.realpath@1.0.0",
      "inflight": "npm:inflight@1.0.5",
      "inherits": "npm:inherits@2.0.1",
      "minimatch": "npm:minimatch@3.0.2",
      "once": "npm:once@1.3.3",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "path-is-absolute": "npm:path-is-absolute@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:highlight.js@8.9.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:history@2.1.2": {
      "deep-equal": "npm:deep-equal@1.0.1",
      "invariant": "npm:invariant@2.2.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "query-string": "npm:query-string@3.0.3",
      "warning": "npm:warning@2.1.0"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:iconv-lite@0.4.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:in-publish@2.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:inflight@1.0.5": {
      "once": "npm:once@1.3.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "wrappy": "npm:wrappy@1.0.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:invariant@2.2.1": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:isomorphic-fetch@2.2.1": {
      "node-fetch": "npm:node-fetch@1.5.3",
      "whatwg-fetch": "npm:whatwg-fetch@1.0.0"
    },
    "npm:jquery@3.1.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:lodash.assign@4.0.9": {
      "lodash.keys": "npm:lodash.keys@4.0.7",
      "lodash.rest": "npm:lodash.rest@4.0.3"
    },
    "npm:lodash.rest@4.0.3": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:loose-envify@1.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "js-tokens": "npm:js-tokens@1.0.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:minimatch@3.0.2": {
      "brace-expansion": "npm:brace-expansion@1.1.6",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:node-fetch@1.5.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "encoding": "npm:encoding@0.1.12",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "is-stream": "npm:is-stream@1.1.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
    "npm:once@1.3.3": {
      "wrappy": "npm:wrappy@1.0.2"
    },
    "npm:pako@0.2.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-is-absolute@1.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process-nextick-args@1.0.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.6": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:promise@7.1.1": {
      "asap": "npm:asap@2.0.4",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:query-string@3.0.3": {
      "strict-uri-encode": "npm:strict-uri-encode@1.1.0"
    },
    "npm:react-dom@15.3.0": {
      "react": "npm:react@15.3.0"
    },
    "npm:react-highlight@0.8.0": {
      "highlight.js": "npm:highlight.js@8.9.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "react": "npm:react@15.3.0",
      "react-dom": "npm:react-dom@15.3.0"
    },
    "npm:react-markdown@2.4.2": {
      "commonmark": "npm:commonmark@0.24.0",
      "commonmark-react-renderer": "npm:commonmark-react-renderer@4.2.4",
      "in-publish": "npm:in-publish@2.0.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.0"
    },
    "npm:react-router@2.6.1": {
      "history": "npm:history@2.1.2",
      "hoist-non-react-statics": "npm:hoist-non-react-statics@1.2.0",
      "invariant": "npm:invariant@2.2.1",
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.0",
      "warning": "npm:warning@3.0.0"
    },
    "npm:react@15.3.0": {
      "fbjs": "npm:fbjs@0.8.3",
      "loose-envify": "npm:loose-envify@1.2.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:readable-stream@2.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-shims": "npm:buffer-shims@1.0.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "process-nextick-args": "npm:process-nextick-args@1.0.7",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util-deprecate": "npm:util-deprecate@1.0.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:ua-parser-js@0.7.10": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util-deprecate@1.0.2": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@2.1.0": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:warning@3.0.0": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:yamljs@0.2.8": {
      "argparse": "npm:argparse@1.0.7",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "glob": "npm:glob@7.0.5",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    }
  }
});
